### ISSUE TITLE
Launcher crashes when clicking settings

### ISSUE THREAD

**Issue by Ptikev** [gorilla-devs/GDLauncher#392] opened 2020-04-10 13:15 UTC
Describe the bug
Since I installed a second instance, whenever i click the upper right cog to open settings the launcher crashes and prompts me to restart. It worked just fine with only one instance. I can still access settings for specific instances by right clicking them and choosing manage, i just cant access the launcher's settings screen any more.

To Reproduce

Fresh install of last stable version
I added Enigmatica 4 and could still access settings
Then I installed Journey Across The Void and it crashes everytime i click on settings

Possible solutions
Fresh install of the launcher, the packs and my mods and settings maybe ?

Operating System:
OS: Windows 10 64
Version 10 uppdate 1909

Im not sure if the launcher outputs crash logs and where, if so let me know where and i'll provide logs.

**Comment by AzureDoom** [comment] 2020-04-10 13:18
Dupe of #256

**Comment by Ptikev** [comment] 2020-04-10 15:06
How is it a dupe of #256 ? my launcher logs me in just fine, my issue is it crashes when i click on settings

**Comment by AzureDoom** [comment] 2020-04-10 15:14
Because it is the same cause: being logged out. If you would relog it would allow you to access it. Therefore dupe of #256

**Comment by Ptikev** [comment] 2020-04-10 15:28
Oh ok thanks for the fix, guess i'll just wait for next update and login manually until then.

**Closed as completed** 2020-04-11 03:25 UTC
