### ISSUE TITLE
Minecraft Forge 1.17.1 not working

### ISSUE THREAD

**Issue by tbellyeah1** [gorilla-devs/GDLauncher#1028] opened 2021-08-17 14:12 UTC
Whenever I try to make a forge 1.17.1 instance, it gets stuck at downloading forge installer, and then wont do anything.
When I exit out while it is stuck, and then reload the page, it says that it was missing something, and wouldn't load.
Can you Please Do something to help? Or is this a community wide problem?

**Comment by hypherionmc** [comment] 2021-08-17 14:22
Duplicate of #1008. We're working on a fix

**Comment by hypherionmc** [comment] 2021-08-21 22:35
Fixed in release 1.1.12+

**Closed as completed by hypherionmc** 2021-08-21 22:35 UTC

**Comment by tbellyeah1** [comment] 2021-08-25 13:12
tysm i can now use forge 1.17.1! tysm
