### ISSUE TITLE
context menu does not float up when at bottom of launcher.

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#515] opened 2020-06-07 03:33 UTC
gdl 1.0.6 on Linux

![image](https://user-images.githubusercontent.com/3880072/83959704-b3bded80-a845-11ea-8545-dd5b40235111.png)

**Comment by ChaseIngebritson** [comment] 2020-06-28 17:59
Could not reproduce this issue on v1.0.8 in Windows 10.

![2020-06-28 12_51_40-Instance js - GDLauncher - Visual Studio Code  Administrator](https://user-images.githubusercontent.com/11217065/85954627-83e2a100-b93e-11ea-83ef-92e04f0486a2.png)

Looks like this was resolved in #542 and released in [v1.0.8](https://github.com/gorilla-devs/GDLauncher/releases/tag/v1.0.8).

**Comment by kreezxil** [comment] 2020-06-30 10:58
nice

**Closed as completed** 2020-07-08 08:57 UTC
