### ISSUE TITLE
Instances Groups!

### ISSUE THREAD

**Issue by HeadMonitor** [gorilla-devs/GDLauncher#385] opened 2020-04-06 21:36 UTC
Something that i would really like added to GDLauncher is instance groups so it can be a bit more organized.  For example i have two instances with the same mods but different versions. The folder could be really handy there.

**Comment by TOLoneWolf** [comment] 2020-04-06 21:45
Duplicate of #271

**Closed as completed** 2020-04-15 17:11 UTC
Labels: Type: Feature
