### ISSUE TITLE
when ever i try to create a instances it just shows this 

### ISSUE THREAD

**Issue by ExcelDriftt21** [gorilla-devs/GDLauncher#845] opened 2021-04-20 22:25 UTC
![Screen Shot 2021-04-20 at 3 24 27 PM](https://user-images.githubusercontent.com/82901779/115471308-9b9c5600-a1ec-11eb-8980-4f6fb3040a29.png)

**Comment by TOLoneWolf** [comment] 2021-04-20 22:53
duplicate of #841

**Closed as completed by TOLoneWolf** 2021-04-20 22:53 UTC
