### ISSUE TITLE
Remember Me does not remember its own setting

### ISSUE THREAD

**Issue by Discomanco** [gorilla-devs/GDLauncher#290] opened 2020-01-05 09:03 UTC
**Describe the bug**
Due to the auto-login issue already marked by multiple threads, I stopped using the Remember Me setting. However, it does not remember if you untick the Remember Me box, and will re-enable itself once you go back to the Login screen

**To Reproduce**
1. Go to Login Screen
2. Untick "Remember Me"
3. Login with your credentials
4. Log back out
5. "Remember Me" is now ticked again.

Also when turning the computer back on after the night, starting the GDLauncher still logged me in with a blank user

**Expected behavior**
"Remember Me" should remember if it's active or not

**Screenshots**
https://gfycat.com/gaseouselderlyafricanrockpython

**Operating System:**
 - OS: Windows 10

**Additional context**
This whole "Auto-login" issue actually makes it possible to use and play minecraft without a valid account..

**Comment by Discomanco** [comment] 2020-01-07 14:39
Ofc just to note, still a thing in 0.12.4

**Comment by TOLoneWolf** [comment] 2020-02-11 05:36
~duplicate of issue #265~
Edit:
Not a duplicate. 
Related bug of issue #265

**Comment by Discomanco** [comment] 2020-02-11 17:56
What the thread is originally is about (Remember Me re-ticking itself), is not a duplicate. At least not of #265

**Closed as completed** 2020-04-15 17:24 UTC
Labels: Type: Bug, Status: Next Release
