### ISSUE TITLE
Cant not download mods that have 3rd downloads turned off

### ISSUE THREAD

**Issue by Dijkstra1** [gorilla-devs/GDLauncher#1456] opened 2022-09-25 01:07 UTC
- [a ] I searched the issue tracker for other issues covering my case
- [ ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)
No this is not an issue with GD its any issue with curse forge 

**Describe the bug**
When GD opens the browser to download the last few mods that have 3rd downloads turned off instead of the download page loading curse is doing a "security" check to see if i am bot but never passes and the page just keeps reloading 

**To Reproduce**
1. Start a pack dowload that use mods that have third downloads turned 
2. Click the download button to open the integrated  browser 
3. wait
4. wait some more
5. ....

**Expected behavior**
Curse not block downloads from GD 

**Possible solutions**
- Faking user agent might work
- Provide me with download likes to download in my browser and folder to put the files in not ideal but would work

**Screenshots**
![image](https://user-images.githubusercontent.com/94000517/192123809-d51dba9b-833f-47a1-966a-08d2c5a98163.png)

![image](https://user-images.githubusercontent.com/94000517/192123814-ef9e727e-47e1-4c22-907a-1b6854ad2a03.png)

**Operating System:**
- OS: Linux
- Launcher Version: 1.1.29
- Java Version: GD provided 
- Minecraft Version: 1.19.2 but guess this would affect all versions 
- Mod Loader: Forge

**Comment by tonylizj** [comment] 2022-12-24 08:09
I had the same issue, managed to bypass this by manually copying the jar in after the directories were created but before the opted-out mods list popup shows up. Also maybe a duplicate of #1367?

**Comment by Eskaan** [comment] 2022-12-24 11:53
Yes, this is a dup.

**Closed by Eskaan** 2022-12-24 11:53 UTC
Labels: Type: Bug
