### ISSUE TITLE
Unable to connect when updating Forge and cancelling when prompted to cancel/retry deletes entire instance

### ISSUE THREAD

**Issue by EatFecalMatterAndDie** [gorilla-devs/GDLauncher#1440] opened 2022-08-28 03:49 UTC
**Describe the bug**
Error connecting to Maven servers (unable to connect) when updating Forge prompts user to Cancel or Retry. Instance shows as 0% updated. Selecting cancel nukes the entire instance.

**To Reproduce**
1. I can't say for sure as I don't care to try making this happen again, so see description for best guess.

**Expected behavior**
Clicking Cancel cancels the update rather than deleting the instance

**Possible solutions**
Make the program not nuke an instance when cancelling an update, or if this is for some reason intentional or un-avoidable, warn the user.

**Screenshots**
N/A

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: ~~17.0.3.1~~ 8.0.3410.10 on system, not sure if instance used that or GDLauncher provided Java
- Minecraft Version: 1.18.2
- Mod Loader: Forge 40.1.73 'Updating' to 40.1.74
- GDLauncher Version: One update behind, but changelogs mention nothing of a bug like this being fixed

**Additional context**
This makes me immeasurably angry (username not related).

**Comment by Eskaan** [comment] 2022-08-28 07:53
Duplicate of #1288

**Closed by Eskaan** 2022-08-28 07:53 UTC
